"""Add persistent user storage

Revision ID: 3250d522637a
Revises: 
Create Date: 2025-06-05 15:16:49.889461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3250d522637a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_type', sa.Enum('GENERAL_UPDATE', 'PRESENTATIONS_AND_UPDATES', 'OTHER', name='meetingtype'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_id'), 'meeting', ['id'], unique=False)
    op.create_table('facultyupdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('announcements_text', sa.Text(), nullable=True),
    sa.Column('announcement_type', sa.Enum('GENERAL', 'URGENT', 'DEADLINE', name='announcementtype'), nullable=False),
    sa.Column('projects_text', sa.Text(), nullable=True),
    sa.Column('project_status_text', sa.Text(), nullable=True),
    sa.Column('faculty_questions', sa.Text(), nullable=True),
    sa.Column('is_presenting', sa.Boolean(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facultyupdate_id'), 'facultyupdate', ['id'], unique=False)
    op.add_column('fileupload', sa.Column('faculty_update_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fileupload', 'facultyupdate', ['faculty_update_id'], ['id'], ondelete='CASCADE')
    op.add_column('studentupdate', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.add_column('studentupdate', sa.Column('meeting_notes', sa.Text(), nullable=True))
    op.add_column('studentupdate', sa.Column('will_present', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'studentupdate', 'meeting', ['meeting_id'], ['id'], ondelete='SET NULL')
    # Add full_name as nullable first, then update existing records
    op.add_column('user', sa.Column('full_name', sa.String(length=100), nullable=True))
    
    # Update existing users with a default full_name based on username
    op.execute("UPDATE \"user\" SET full_name = username WHERE full_name IS NULL")
    
    # Now make it non-nullable
    op.alter_column('user', 'full_name', nullable=False)
    op.add_column('user', sa.Column('preferred_email', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'preferred_email')
    op.drop_column('user', 'full_name')
    op.drop_constraint(None, 'studentupdate', type_='foreignkey')
    op.drop_column('studentupdate', 'will_present')
    op.drop_column('studentupdate', 'meeting_notes')
    op.drop_column('studentupdate', 'meeting_id')
    op.drop_constraint(None, 'fileupload', type_='foreignkey')
    op.drop_column('fileupload', 'faculty_update_id')
    op.drop_index(op.f('ix_facultyupdate_id'), table_name='facultyupdate')
    op.drop_table('facultyupdate')
    op.drop_index(op.f('ix_meeting_id'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###