"""Add presentation assignment file attachments

Revision ID: a7e266bf84b2
Revises: 7b0ef1220e47
Create Date: 2025-06-26 10:15:48.047896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7e266bf84b2'
down_revision = '7b0ef1220e47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('announcement_type', sa.Enum('GENERAL', 'ACADEMIC', 'ADMINISTRATIVE', 'RESEARCH', 'EVENT', 'URGENT', name='announcementtype'), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_updates_id'), 'faculty_updates', ['id'], unique=False)
    op.create_table('student_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('refined_content', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_updates_id'), 'student_updates', ['id'], unique=False)
    op.create_table('presentation_assignment_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_assignment_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('file_category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_assignment_id'], ['presentation_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_assignment_files_id'), 'presentation_assignment_files', ['id'], unique=False)
    op.create_index(op.f('ix_assigned_presentations_id'), 'assigned_presentations', ['id'], unique=False)
    op.drop_constraint('assigned_presentations_user_id_fkey', 'assigned_presentations', type_='foreignkey')
    op.create_foreign_key(None, 'assigned_presentations', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fileupload', 'agendaitem', ['agenda_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('meeting', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('meeting_created_by_fkey', 'meeting', type_='foreignkey')
    op.create_foreign_key(None, 'meeting', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    # Create the enum type first
    presentationtype_enum = sa.Enum('CASUAL', 'MOCK_DEFENSE', 'PRE_CONFERENCE', 'THESIS_PROPOSAL', 'DISSERTATION_DEFENSE', 'JOURNAL_CLUB', 'RESEARCH_UPDATE', name='presentationtype')
    presentationtype_enum.create(op.get_bind(), checkfirst=True)
    
    # Convert column using USING clause for proper casting
    op.execute("ALTER TABLE presentation_assignments ALTER COLUMN presentation_type TYPE presentationtype USING presentation_type::presentationtype")
    op.alter_column('presentation_assignments', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentation_assignments', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('presentation_assignments', 'presentation_type',
               existing_type=sa.Enum('CASUAL', 'MOCK_DEFENSE', 'PRE_CONFERENCE', 'THESIS_PROPOSAL', 'DISSERTATION_DEFENSE', 'JOURNAL_CLUB', 'RESEARCH_UPDATE', name='presentationtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.create_foreign_key('meeting_created_by_fkey', 'meeting', 'user', ['created_by'], ['id'])
    op.alter_column('meeting', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'fileupload', type_='foreignkey')
    op.drop_constraint(None, 'assigned_presentations', type_='foreignkey')
    op.create_foreign_key('assigned_presentations_user_id_fkey', 'assigned_presentations', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_assigned_presentations_id'), table_name='assigned_presentations')
    op.drop_index(op.f('ix_presentation_assignment_files_id'), table_name='presentation_assignment_files')
    op.drop_table('presentation_assignment_files')
    op.drop_index(op.f('ix_student_updates_id'), table_name='student_updates')
    op.drop_table('student_updates')
    op.drop_index(op.f('ix_faculty_updates_id'), table_name='faculty_updates')
    op.drop_table('faculty_updates')
    # ### end Alembic commands ###